# Generated by Django 3.1.6 on 2021-03-01 15:26

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_roll', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('s_father_name', models.CharField(max_length=30)),
                ('s_birth', models.DateField()),
                ('s_phone', models.IntegerField(unique=True)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_image', models.ImageField(upload_to='studentImages')),
            ],
        ),
    ]
