# Generated by Django 3.1.6 on 2021-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210301_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_roll',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
